### ISSUE TITLE
extra spalte

### ISSUE THREAD

**Issue by manasii1812** [JustforFun2112/WAGitHubGruppe11#11]
In der csv File gibt's ein extra Spalte am links, die genau wie ID spalte aussieht. ist es gemeint oder einen Fehler?

**Comment by felixhansch** [comment]
Glaube die erste Spalte ohne Überschrift ist nicht nötig.

**Comment by felixhansch** [comment]
In meiner erstellten Tabelle aus den Daten von Aufgabe 1 ist die extra Spalte jetzt weg. Die Daten hat Shaban als .pdf hochgeladen. Wenn Aufgabe 3 fertig ist, könnt ihr dann mit Auswerten anfangen ^^.
