### ISSUE TITLE
Aufgabe_3

### ISSUE THREAD

**Issue by Shaban92** [JustforFun2112/WAGitHubGruppe11#15]
Ich beschäftige mich mit dem Teil(e) von der dritte Aufgabe, ich sag Bescheid um den Konflikt von Coden zu vermeiden

**Comment by JustforFun2112** [comment]
Ich Kümmere mich um die 3f), sollten bei mir probleme entstehen melde ich das nochmal

**Comment by Shaban92** [comment]
sehr gut

**Comment by Shaban92** [comment]
Ich stelle mir die Frage, soll die Funktion kategorie_x in Teil(e) einstellbar implementieren um mehr als nur drei Kategorie ( „niedrig“, „mittel“, „hoch“)?

oder es ist genug erst mal so?

**Comment by JustforFun2112** [comment]
#16  Problem was auftritt ist sobald wir die Aufgabenteile mergen werden teilweise Dateiname und Logikelemente eingefügt.

um das zu beheben schlage ich eine Manuelle korrektur in Github vor.

**Comment by Shaban92** [comment]
ich hoffe, das Problem ist schon gelöst, und jetzt keinen Konflikt bei dem neuen pull request entsteht
