### ISSUE TITLE
Frage zur Aufgabeneinteilung

### ISSUE THREAD

**Issue by felixhansch** [JustforFun2112/WAGitHubGruppe11#2]
Ich würde gerne an der ersten Aufgabe arbeiten. Möchte jemand mit mir arbeiten? Bis morgen versuche ich einen ersten R Code hochzuladen!

( ͡° ͜ʖ ͡° )

**Comment by seriadi12** [comment]
Ich würde mit Aufgabe 3 anfangen

**Comment by Shaban92** [comment]
ich würde gerne mit Felix an der ersten Aufgabe mitmachen

**Comment by felixhansch** [comment]
Habe jetzt mit @seriadi12 die 3a) gemacht.
Fertiger Code ist in Aufgaben drin.

ʘ‿ʘ

**Comment by manasii1812** [comment]
Womit soll ich anfangen, ich meine welche aufgabeteil habt ihr schon dann kann ich mit dem nächsten beginnen?

**Comment by Shaban92** [comment]
> Womit soll ich anfangen, ich meine welche aufgabeteil habt ihr schon dann kann ich mit dem nächsten beginnen?

wir haben die erste Aufgabe fast fertig gemacht , und wie oben von Felix berichtet wurde, 3a) ist anscheinend fertig.

du kannst gerne vielleicht 3b) bearbeiten , falls keiner sich gemeldet hat bzw. was aktualisiert

**Comment by seriadi12** [comment]
Ich hab 3 c) hochgeladen bei mir im Branch.Ihr könnt euch das mal ansehen und kommentieren.Jemand müsste 3 b) machen.

**Comment by JustforFun2112** [comment]
womit soll ich dann weiter machen? was steht noch offen?

**Comment by felixhansch** [comment]
Aufgabe 3 müssen noch ein Paar Funktionen geschrieben werden, bzw. danach die Auswertung der csv. müsst ihr dann zu dritt machen.
