### ISSUE TITLE
Probleme mit pull requests

### ISSUE THREAD

**Issue by Shaban92** [JustforFun2112/WAGitHubGruppe11#25]
#24 
Anscheinend ist von mir aus Versehen auf falsche Branche gepusht?
kann von Felix bitte überprüft werden, ob alles in Ordnung ist ?

**Comment by felixhansch** [comment]
Verstehe ich selbst nicht. Was genau ist [revert-20-Felix-Aufgaben]?

**Comment by felixhansch** [comment]
Habe jetzt mal [revert-20-Felix-Aufgaben] Aufgaben gelöscht, keine Ahnung woher diese Branch kommt. Zu deinem Pull Request #24: Du hast einfach deinen Branch "Shaban-Aufgaben" mit den Daten aus "Aufgaben" überschrieben. Am besten ist, wenn du einfach immer einen neuen Branch machst und ach dem Pull Request löscht und einen neuen machst, so mache ich es zumindest. Verstehe aber nicht genau was ich kontrollieren soll/ wo das Problem ist. Könntest du mir das genauer erklären? @Shaban92
