### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by seriadi12** [JustforFun2112/WAGitHubGruppe11#27]
Ich habe Aufgabe 4 angefangen die Funktionen aus 3 a) zu benutzen.Ihr könnt in meinem Branch gucken.Ich merge das später mit dem Aufgabenbranch.

**Comment by felixhansch** [comment]
Nicht wundern, ich fasse gleich nochmal die 3a zusammen. Es sollte sich aber nichts ändern.

**Comment by JustforFun2112** [comment]
ich mache auch weiter an der Aufgabe, und sollten Komplikationen entstehen werde ich das hier ins Issue schreiben.
