### ISSUE TITLE
neue Branche automatisch erstellt wurde.

### ISSUE THREAD

**Issue by Shaban92** [JustforFun2112/WAGitHubGruppe11#8]
kann mir jemand bitte erklären, warum sind bei mir zwei Branchen geworden obwohl ich nur eine eine Einzige erstellt habe. woran liegt es, damit ich es vermeide.

**Comment by felixhansch** [comment]
Da habe ich auch keine Ahnung. Eine weiter Frage dazu: Müssen wir die Branches am Ende behalten oder können wir die löschen. Inwiefern werden unsere Überarbeitungen in den Branches 'gespeichert'?
